name: Ntfy Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Ntfy notification
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }}
        run: |
          curl -d "A new commit was pushed to the main branch by $GITHUB_ACTOR. ✈️" \
          $NTFY_URL
