name: Ntfy Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Ntfy notification
        env:
          NTFY_URL: ${{ secrets.NTFY_URL }} # Make sure to set this to your ntfy.sh topic URL in Github Secrets! (e.g., https://ntfy.sh/my_secret_topic)
        run: |
          curl -d "A new commit was pushed to the main branch by $GITHUB_ACTOR. :smile:" \
          $NTFY_URL
